### ISSUE TITLE
Proper Description

### ISSUE THREAD

**Issue by SuyashSonawane** [dscpccoe/join-us#30]
**Is your feature request related to a problem? Please describe.**
The description can be a bit more informative

**Describe the solution you'd like**
I can add a more descriptive description 

**Describe alternatives you've considered**
NA

**Additional context**
![image](https://user-images.githubusercontent.com/35629339/93705341-0c39a200-fb3a-11ea-9c58-d91e11fd42c2.png)

**Comment by tejasmorkar** [comment]
Awesome... you can work on it

**Comment by SuyashSonawane** [comment]
On it
