### ISSUE TITLE
decription needed

### ISSUE THREAD

**Issue by SuyashSonawane** [dscpccoe/join-us#9]
**Is your feature request related to a problem? Please describe.**
The website doesn't make any sense without a proper description

**Describe the solution you'd like**
I want to add a description

**Describe alternatives you've considered**
No

**Additional context**
Add any other context or screenshots about the feature request here.NA
![image](https://user-images.githubusercontent.com/35629339/93666007-5bc79180-fa98-11ea-84d9-5b4de479ad98.png)

**Comment by tejasmorkar** [comment]
Good idea @SuyashSonawane 

Do you want to work on it or should I assign someone else?

**Comment by SuyashSonawane** [comment]
I can work on it !!

**Comment by tejasmorkar** [comment]
Okay go forward with it!
